//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinIPChanger.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinIPChanger.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Name | DHCP | IP Address | Subnet Mask | Default Gateway | DNS Servers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdapterHeader {
            get {
                return ResourceManager.GetString("AdapterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------------------------------------------------------------------------------ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdapterHeaderSeparator {
            get {
                return ResourceManager.GetString("AdapterHeaderSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} | {1} | {2} | {3} | {4} | {5} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdapterListFormat {
            get {
                return ResourceManager.GetString("AdapterListFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP-Enabled network connection information is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdapterNotFound {
            get {
                return ResourceManager.GetString("AdapterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WinIPChangerConsole [/S | /V] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMessageCommand {
            get {
                return ResourceManager.GetString("HelpMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /S  All IP-Enabled network connection information is displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMessageOptionS {
            get {
                return ResourceManager.GetString("HelpMessageOptionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /V  All IP-Enabled network connection information is displayed. (Same as &apos;/S&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMessageOptionV {
            get {
                return ResourceManager.GetString("HelpMessageOptionV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can get and set the network adapter settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMessageTitle {
            get {
                return ResourceManager.GetString("HelpMessageTitle", resourceCulture);
            }
        }
    }
}
